language: node_js
node_js: '8'
cache: yarn
before_install:
  - npm config set "//npm.fontawesome.com/:_authToken" $FA_TOKEN
  - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
install: yarn --pure-lockfile
script:
  - yarn test
  - yarn build
deploy:
  skip_cleanup: true
  provider: s3
  region: eu-west-1
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: moeriki.com
  local-dir: dist/
  on:
    repo: Moeriki/awesome-cv
